# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=30, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('chart_no', models.IntegerField(db_column='CHART_NO', primary_key=True, serialize=False)),
                ('pt_name', models.CharField(db_column='PT_NAME', max_length=20)),
                ('id_no', models.CharField(blank=True, db_column='ID_NO', max_length=10, null=True)),
                ('id_no_ok', models.CharField(db_column='ID_NO_OK', max_length=1)),
                ('photocopy', models.CharField(db_column='PHOTOCOPY', max_length=1)),
                ('birth_date', models.CharField(blank=True, db_column='BIRTH_DATE', max_length=7, null=True)),
                ('first_view_date', models.CharField(blank=True, db_column='FIRST_VIEW_DATE', max_length=7, null=True)),
                ('last_view_date', models.CharField(blank=True, db_column='LAST_VIEW_DATE', max_length=7, null=True)),
                ('create_date', models.CharField(db_column='CREATE_DATE', max_length=7)),
                ('create_clerk', models.CharField(db_column='CREATE_CLERK', max_length=6)),
                ('modify_date', models.CharField(blank=True, db_column='MODIFY_DATE', max_length=7, null=True)),
                ('modify_clerk', models.CharField(blank=True, db_column='MODIFY_CLERK', max_length=6, null=True)),
                ('sex', models.CharField(db_column='SEX', max_length=1)),
                ('pt_type', models.IntegerField(db_column='PT_TYPE')),
                ('location', models.CharField(blank=True, db_column='LOCATION', max_length=6, null=True)),
                ('last_xray_date', models.CharField(blank=True, db_column='LAST_XRAY_DATE', max_length=7, null=True)),
                ('last_exam_date', models.CharField(blank=True, db_column='LAST_EXAM_DATE', max_length=7, null=True)),
                ('med_pack', models.CharField(db_column='MED_PACK', max_length=1)),
                ('foreign', models.CharField(blank=True, db_column='FOREIGN', max_length=1, null=True)),
                ('merge_to', models.DecimalField(blank=True, db_column='MERGE_TO', decimal_places=0, max_digits=7, null=True)),
                ('emp_no', models.CharField(blank=True, db_column='EMP_NO', max_length=6, null=True)),
                ('who_disc', models.CharField(blank=True, db_column='WHO_DISC', max_length=6, null=True)),
                ('inp_discount_ptr', models.IntegerField(blank=True, db_column='INP_DISCOUNT_PTR', null=True)),
                ('opd_discount_ptr', models.IntegerField(blank=True, db_column='OPD_DISCOUNT_PTR', null=True)),
                ('died_trans_clerk', models.CharField(blank=True, db_column='DIED_TRANS_CLERK', max_length=6, null=True)),
                ('died_trans_date', models.CharField(blank=True, db_column='DIED_TRANS_DATE', max_length=7, null=True)),
                ('died_cert_no', models.CharField(blank=True, db_column='DIED_CERT_NO', max_length=10, null=True)),
                ('died_reason', models.CharField(blank=True, db_column='DIED_REASON', max_length=100, null=True)),
                ('died_date', models.CharField(blank=True, db_column='DIED_DATE', max_length=7, null=True)),
                ('vs_when_died', models.CharField(blank=True, db_column='VS_WHEN_DIED', max_length=6, null=True)),
                ('comefrom_no', models.CharField(blank=True, db_column='COMEFROM_NO', max_length=6, null=True)),
                ('locking_clerk', models.CharField(blank=True, db_column='LOCKING_CLERK', max_length=6, null=True)),
                ('locking_datetime', models.CharField(blank=True, db_column='LOCKING_DATETIME', max_length=11, null=True)),
                ('died_time', models.CharField(blank=True, db_column='DIED_TIME', max_length=4, null=True)),
                ('blood', models.CharField(blank=True, db_column='BLOOD', max_length=5, null=True)),
                ('newborn_id_no', models.CharField(blank=True, db_column='NEWBORN_ID_NO', max_length=10, null=True)),
                ('newborn_birth_date', models.CharField(blank=True, db_column='NEWBORN_BIRTH_DATE', max_length=7, null=True)),
                ('newborn_note', models.CharField(blank=True, db_column='NEWBORN_NOTE', max_length=1, null=True)),
                ('first_hr_date', models.CharField(blank=True, db_column='FIRST_HR_DATE', max_length=7, null=True)),
                ('grind', models.CharField(db_column='GRIND', max_length=1)),
                ('spec_no', models.CharField(blank=True, db_column='SPEC_NO', max_length=2, null=True)),
                ('remark', models.TextField(blank=True, db_column='REMARK', null=True)),
                ('childbirth_date', models.CharField(blank=True, db_column='CHILDBIRTH_DATE', max_length=7, null=True)),
                ('ic_card_no', models.CharField(blank=True, db_column='IC_CARD_NO', max_length=12, null=True)),
                ('g_times', models.IntegerField(blank=True, db_column='G_TIMES', null=True)),
                ('p_times', models.IntegerField(blank=True, db_column='P_TIMES', null=True)),
                ('sendmsg_all_flag', models.CharField(blank=True, db_column='SENDMSG_ALL_FLAG', max_length=1, null=True)),
                ('last_sendmsg_date', models.CharField(blank=True, db_column='LAST_SENDMSG_DATE', max_length=7, null=True)),
                ('inj_sendmsg_date', models.CharField(blank=True, db_column='INJ_SENDMSG_DATE', max_length=7, null=True)),
                ('breat_sendmsg_date', models.CharField(blank=True, db_column='BREAT_SENDMSG_DATE', max_length=7, null=True)),
                ('sensitive_label', models.CharField(blank=True, db_column='SENSITIVE_LABEL', max_length=2, null=True)),
                ('lmp_date', models.CharField(blank=True, db_column='LMP_DATE', max_length=7, null=True)),
                ('aborigine', models.CharField(blank=True, db_column='ABORIGINE', max_length=1, null=True)),
                ('privacy_flag', models.CharField(blank=True, db_column='PRIVACY_FLAG', max_length=1, null=True)),
                ('dnr_flag', models.CharField(blank=True, db_column='DNR_FLAG', max_length=1, null=True)),
                ('dnr_sign', models.CharField(blank=True, db_column='DNR_SIGN', max_length=1, null=True)),
                ('raiseorg_flag', models.CharField(blank=True, db_column='RAISEORG_FLAG', max_length=1, null=True)),
                ('is_cs_his', models.CharField(blank=True, db_column='IS_CS_HIS', max_length=2, null=True)),
            ],
            options={
                'db_table': 'chart',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Requisition',
            fields=[
                ('req_no', models.CharField(db_column='REQ_NO', max_length=13, primary_key=True, serialize=False)),
                ('req_datetime', models.CharField(db_column='REQ_DATETIME', max_length=13)),
                ('print_times', models.IntegerField(db_column='PRINT_TIMES')),
                ('inp_opd', models.CharField(db_column='INP_OPD', max_length=1)),
                ('form_no', models.CharField(db_column='FORM_NO', max_length=2)),
                ('chart_no', models.IntegerField(db_column='CHART_NO')),
                ('serno', models.IntegerField(db_column='SERNO')),
                ('order_date', models.CharField(db_column='ORDER_DATE', max_length=7)),
                ('processed', models.CharField(db_column='PROCESSED', max_length=1)),
                ('seq_no', models.IntegerField(blank=True, db_column='SEQ_NO', null=True)),
                ('exam_type', models.CharField(blank=True, db_column='EXAM_TYPE', max_length=1, null=True)),
                ('exam_sample', models.CharField(blank=True, db_column='EXAM_SAMPLE', max_length=2, null=True)),
                ('exam_information', models.CharField(blank=True, db_column='EXAM_INFORMATION', max_length=240, null=True)),
                ('sch_date', models.CharField(blank=True, db_column='SCH_DATE', max_length=7, null=True)),
                ('sch_time', models.CharField(blank=True, db_column='SCH_TIME', max_length=4, null=True)),
                ('diagnosis', models.TextField(blank=True, db_column='DIAGNOSIS', null=True)),
                ('pack_type', models.CharField(blank=True, db_column='PACK_TYPE', max_length=1, null=True)),
                ('confirm_datetime', models.CharField(blank=True, db_column='CONFIRM_DATETIME', max_length=11, null=True)),
                ('confirm_clerk', models.CharField(blank=True, db_column='CONFIRM_CLERK', max_length=6, null=True)),
                ('nolend_reason', models.CharField(blank=True, db_column='NOLEND_REASON', max_length=6, null=True)),
                ('stock', models.CharField(blank=True, db_column='STOCK', max_length=6, null=True)),
                ('rel_req_no', models.CharField(blank=True, db_column='REL_REQ_NO', max_length=13, null=True)),
                ('scrap_date', models.CharField(blank=True, db_column='SCRAP_DATE', max_length=7, null=True)),
                ('exam_anti', models.CharField(blank=True, db_column='EXAM_ANTI', max_length=1, null=True)),
                ('exam_datetime', models.CharField(blank=True, db_column='EXAM_DATETIME', max_length=11, null=True)),
                ('rel_req_no_o', models.CharField(blank=True, db_column='REL_REQ_NO_O', max_length=13, null=True)),
                ('processed_date', models.CharField(blank=True, db_column='PROCESSED_DATE', max_length=7, null=True)),
                ('remark', models.CharField(blank=True, db_column='REMARK', max_length=50, null=True)),
                ('check_in_flag', models.CharField(blank=True, db_column='CHECK_IN_FLAG', max_length=1, null=True)),
                ('check_in_datetime', models.CharField(blank=True, db_column='CHECK_IN_DATETIME', max_length=13, null=True)),
            ],
            options={
                'db_table': 'requisition',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('form_no', models.CharField(db_column='FORM_NO', max_length=10, primary_key=True, serialize=False)),
                ('form_name', models.CharField(db_column='FORM_NAME', max_length=50)),
                ('note', models.TextField(blank=True, db_column='NOTE', null=True)),
                ('subtel1', models.CharField(blank=True, db_column='SUBTEL1', max_length=5, null=True)),
                ('subtel2', models.CharField(blank=True, db_column='SUBTEL2', max_length=5, null=True)),
                ('keyin_date', models.CharField(db_column='KEYIN_DATE', max_length=7)),
                ('keyin_clerk', models.CharField(db_column='KEYIN_CLERK', max_length=6)),
            ],
            options={
                'db_table': 'schedule',
                'managed': False,
            },
        ),
    ]
