# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 03:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hismaxdb', '0003'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registerdevice',
            options={},
        ),
        migrations.AlterModelTable(
            name='registerdevice',
            table=None,
        ),
    ]
